language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-28.0.3
    - platform-tools
    - tools
    - android-29
before_install: yes | sdkmanager "platforms;android-29"
script: ./gradlew clean build
