language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - tools
    - android-27
before_install: yes | sdkmanager "platforms;android-27"
script: ./gradlew build
