name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    environment: build
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        check-latest: true
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY  }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD  }}
        REMOTE_CACHE_URL: ${{ secrets.REMOTE_CACHE_URL }}
        REMOTE_CACHE_USER: ${{ secrets.REMOTE_CACHE_USER }}
        REMOTE_CACHE_PASS: ${{ secrets.REMOTE_CACHE_PASS }}
      run: ./gradlew clean build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
