name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        check-latest: true
    - name: Build with Gradle
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_GPGPASSWORD: ${{ secrets.BINTRAY_GPGPASSWORD }}
        BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
      run: ./gradlew clean build
